apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mlops
  name: green-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: green-deploy
  template:
    metadata:
      labels:
        app: green-deploy
    spec:
      containers:
          - name: fastapi-app-container
            image: heyitsrj/mlops-fastapi-app:green
            imagePullPolicy: Always
            ports:
              - containerPort: 8080
            resources:
              requests:
                memory: "70Mi"
                cpu: "50m"
              limits:
                memory: "128Mi"
                cpu: "70m"