apiVersion: v1
kind: Service
metadata:
  namespace: mlops
  name: green-service
spec:
  selector:
    app: green-deploy
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer
