apiVersion: v1
kind: Service
metadata:
  namespace: mlops
  name: fast-api-service
spec:
  selector:
    app: fastapi-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer
